### PR TITLE
He Yi

### PR DESCRIPTION
**Pull request by christianebacani**

### CODE REVIEW

**Comment by christianebacani** [comment]
[heyi_interview_keywords.txt](https://github.com/user-attachments/files/16829429/heyi_interview_keywords.txt)

[heyi_backgrounds.txt](https://github.com/user-attachments/files/16829431/heyi_backgrounds.txt)

**Review by armlynobinguar — CHANGES_REQUESTED** [review]
Clean your dataset.

**Comment by armlynobinguar** [comment]
Redo this pull request, you can submit new PR again @christianebacani with the feature-branch

**Review by armlynobinguar — COMMENTED** [review]
Clean the data, make sure per row has 2-3 sentences or a paragraph.

**Comment by armlynobinguar** [comment]
Create a new pull request, will close this request

**Pull request closed without merging**
