### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Irckyyy**
Act1 and 2

### CODE REVIEW

**Comment by Irckyyy** [comment]
[Act 2 - Joe Biden.txt](https://github.com/user-attachments/files/16573107/Act.2.-.Joe.Biden.txt)
[Act1 - Joe Biden.txt](https://github.com/user-attachments/files/16573108/Act1.-.Joe.Biden.txt)

**Comment by armlynobinguar** [comment]
image Remove this 
image Also remove this one no need to add the combined facts text just tbe content is okimage

remove this certain part in biden about the title of its content, just focus on the in text

**Comment by Irckyyy** [comment]
[Act 2(V2) - Joe Biden.txt](https://github.com/user-attachments/files/16573172/Act.2.V2.-.Joe.Biden.txt)
[Act1(V2) - Joe Biden.txt](https://github.com/user-attachments/files/16573173/Act1.V2.-.Joe.Biden.txt)

here po with the comments made

**Comment by armlynobinguar** [comment]
Do pull request again.

**Pull request closed without merging**
