### PR TITLE
Added Dataset for CL207 By Kristine Shyra Carpio

### PR DESCRIPTION
**Pull request by shycarp**
Added dataset for CL207
Quest 1 Webscrape Competition

Contributor: Kristine Shyra A. Carpio

Source: 
https://www.youtube.com/watch?v=T3aHxp20v0s
https://www.youtube.com/watch?v=Gvw6JU6KdkU

### CODE REVIEW

**Comment by ALGOREX-PH** [comment]
I love this contribution!

**Comment by Turq0ise** [comment]
Support from GDSC MAPÚA! VIVA MAPÚA!

**Comment by JLFBartz** [comment]
Support from GDSC MAPÚA! VIVA MAPÚA!

**Comment by AndreLlena** [comment]
Support from GDSC MAPÚA! VIVA MAPÚA!

**Comment by unawarespecs** [comment]
Good luck!

Support from GDSC MAPÚA! VIVA MAPÚA!

**Comment by ahnyuujin** [comment]
VIVA MAPUA!!

**Comment by curiouscapybara14** [comment]
Support from GDSC MAPÚA! VIVA MAPÚA!!!!!!!!!!!!!! ❤️💛

**Pull request merged**
