### PR TITLE
Task 1 by Aditya Singh

### PR DESCRIPTION
**Pull request by adityasingh-0803**
With the help of google colab scraped the information of ethereum and elon musk

### CODE REVIEW

**Comment by armlynobinguar** [comment]
where's the data?

**Comment by adityasingh-0803** [comment]
I have zipped both files

**Comment by adityasingh-0803** [comment]
i have submitted the zip file under webscraping folder

**Comment by adityasingh-0803** [comment]
I have taken Elon musk and ethereum  :D so how to assign it in folder

**Comment by armlynobinguar** [comment]
create a folder and insert it there and redo the pull request, it would be messy if u do the zip file and its in wrong directory

**Review by armlynobinguar — CHANGES_REQUESTED** [review]
Clean your dataset. There's so many errors and uncleaned part here.

**Comment by adityasingh-0803** [comment]
I have added folder please check

**Pull request merged**
