### PR TITLE
Added dataset for yellow panther

### PR DESCRIPTION
**Pull request by MiguelAlfonsoNeri55555**
Group 6
Try

### CODE REVIEW

**Comment by armlynobinguar** [comment]
please redo this, too many files.image

**Comment by MiguelAlfonsoNeri55555** [comment]
image
Hi, ma'am! Ganito po lumalabas pag kiniklik ko yung fork, idk why

**Comment by armlynobinguar** [comment]
> image Hi, ma'am! Ganito po lumalabas pag kiniklik ko yung fork, idk why

"You already forked the repository"

**Comment by armlynobinguar** [comment]
Create a new pull request, will close this one.

**Pull request closed without merging**
