### PR TITLE
Create Knowledge and Guiding Principles

### PR DESCRIPTION
**Pull request by Theylon**

### CODE REVIEW

**Review by armlynobinguar — CHANGES_REQUESTED** [review]
Is your data related to what kind of info, can you give context to it? and if this is an instruction-based or a knowledge-based dataset?

**Comment by Theylon** [comment]
This is character and personality information, as well as general knowledge expansion and behavior guidance and guidelines

**Comment by armlynobinguar** [comment]
Is this a character card or just the data itself. If it's character card, that should follow this https://virtualprotocol.notion.site/Character-Card-Samples-532af51e0e6a4c65b4a6745895241298

If in case it's a data, there should be column names for the content, behavioral and so on. Please do format it well with column names and resubmit the data here. @Theylon

**Review by Theylon — COMMENTED** [review]
Changes to the correct format

**Comment by armlynobinguar** [comment]
Amazing will approve this. Feel free to now submit it on the app.virtuals.io

**Pull request merged**
