### PR TITLE
Added Dataset for Ansem By Danielle Bagaforo Meer

### PR DESCRIPTION
**Pull request by ALGOREX-PH**
Added dataset for Ansem 
Quest 1 Webscrape Competition

Contributor : Danielle Bagaforo Meer

Source :  https://www.youtube.com/watch?v=rawPXSdUqx0, https://www.youtube.com/watch?v=Ju3InnHRA6Y, https://www.youtube.com/watch?v=Ahs7FL2-ldE

### CODE REVIEW

**Review by armlynobinguar — APPROVED** [review]

**Comment by shycarp** [comment]
Very mindful, very insightful, very demure

**Comment by Turq0ise** [comment]
"Support from GDSC MAPÚA! VIVA MAPÚA!

**Comment by JLFBartz** [comment]
Support from GDSC MAPÚA! VIVA MAPÚA!

**Comment by AndreLlena** [comment]
Support from GDSC MAPÚA! VIVA MAPÚA!

**Comment by unawarespecs** [comment]
Good luck!

Support from GDSC MAPÚA! VIVA MAPÚA!

**Comment by ahnyuujin** [comment]
VIVA MAPUA!! Regards!!

**Comment by gkate78** [comment]
Support from DATA ENGINEERING PHILIPPINES! MABUHAY! Good luck Danielle and Shy!

**Comment by AtlastDeepLearning** [comment]
LETS GOO MEER!!! 
Support from GDSC MAPÚA! VIVA MAPÚA!

**Comment by curiouscapybara14** [comment]
Support from GDSC MAPÚA! VIVA MAPÚA!!!!!!!!!!!!!! ❤️💛

**Pull request merged**
