### PR TITLE
Added dataset for Anthony Pompliano

### PR DESCRIPTION
**Pull request by jemslzr**
Webscrape Chronicles Competition Quest 2

Contributor: Clarisse Jem Salazar
Sources: 
https://cryptonews.net/news/bitcoin/27740390/
https://cryptonews.com.au/news/anthony-pompliano-calls-for-simultaneous-release-of-all-bitcoin-etf-applications-116129/
https://crypto.news/anthony-pompliano-bitcoin-etf-purchases-exceed-daily-production-by-12-5-times/
https://coingape.com/anthony-pompliano-predicts-ai-and-bitcoin-role-in-wealth-creation/
https://www.datawallet.com/crypto/anthony-pompliano-net-worth
https://blockchain.news/news/ant-group-chairman-eric-jing-blockchain-cloud-new-financial-infrastructure
https://www.newswire.ca/news-releases/defi-technologies-ceo-featured-on-the-pomp-podcast-with-crypto-evangelist-anthony-pomp-pompliano-823669901.html
https://techcrunch.com/2022/07/13/longtime-bitcoin-bull-anthony-pompliano-launches-crypto-hiring-firm-inflection-points-with-12-6m-raise/

### CODE REVIEW

**Comment by jhonroyilao** [comment]
slayeddddd <33

**Comment by jsmnpncn** [comment]
omg ang amazing, grabe naman ang effort!!

**Comment by Enami345** [comment]
Sheeesh!

**Comment by vysonvy** [comment]
coding on top 👌🏻✨

**Comment by Irckyyy** [comment]
solidddd

**Comment by tel-austral** [comment]
very masipag, very mindful, very nice!!

**Comment by arkzxk** [comment]
Eyyyy, ang effort naman!!

**Comment by jjangmyeonn** [comment]
niceee, congraaats!!!

**Comment by jaedone** [comment]
well done!!! Congratssss!!!

**Comment by ejldgm** [comment]
grabe, batak masiyado!

**Comment by JLA35** [comment]
Congrats!!! 🎉

**Pull request merged**
